<?php

declare(strict_types=1);

use Prism\Mcp\Support\ToolDefinition;

/**
 * The cross-language digest corpus from `prism-parity`.
 *
 * This package is the REFERENCE for that suite, so the goldens below were
 * generated by executing this very code — which makes this file's job narrower
 * and more specific than the ports' equivalents. It is not proving the digest
 * is right. It is proving the corpus has not drifted away from the code it was
 * generated from, so that when a port asserts "I match the reference", the
 * thing it matched is still what the reference produces.
 *
 * Without this, the ports' tests would be pinned to a snapshot of PHP that PHP
 * itself had moved on from, and every one of them would stay green while the
 * claim they encode quietly stopped being true.
 */
function digestCorpus(): array
{
    return json_decode(
        (string) file_get_contents(__DIR__.'/../fixtures/mcp-tool-digest.json'),
        true,
        512,
        JSON_THROW_ON_ERROR,
    )['cases'];
}

it('is the whole suite, not a subset someone trimmed to green', function (): void {
    expect(digestCorpus())->toHaveCount(10);
});

it('still produces the digest the corpus recorded for it', function (): void {
    foreach (digestCorpus() as $case) {
        expect(ToolDefinition::from('conformance', $case['payload'])->digest())
            ->toBe($case['digest']['php'], $case['id'].' — '.$case['title']);
    }
});

it('still DIFFERS from the ports exactly where the corpus says it does', function (): void {
    // Asserted from this side too, not left to the ports. A change here that
    // accidentally converged the reference onto the ports' encoding would
    // otherwise be caught only in two other repositories, on someone else's
    // next run — and this is the repository whose output the pin is generated
    // from.
    foreach (digestCorpus() as $case) {
        $produced = ToolDefinition::from('conformance', $case['payload'])->digest();

        $case['agrees']
            ? expect($produced)->toBe($case['digest']['ts'], $case['id'])
            : expect($produced)->not->toBe($case['digest']['ts'], $case['id']);
    }
});

it('names the divergent rows, so the count cannot drift silently', function (): void {
    $diverging = array_values(array_map(
        fn (array $case): string => $case['id'],
        array_filter(digestCorpus(), fn (array $case): bool => $case['agrees'] === false),
    ));

    expect($diverging)->toBe(['dig-0002', 'dig-0003', 'dig-0007']);
});
